### ISSUE TITLE
Request: Docker-ize the application and push to the Docker Registry

### ISSUE THREAD

**Issue by Phrohdoh** [JackMorrissey/beyond-rule-4#2]
It would be awesome (and much easier) to just run `docker run beyond-rule-4` on a host machine (such as a raspberry pi on a home network).

**Comment by Phrohdoh** [comment]
Taking the nginx config and `Dockerfile` from https://github.com/avatsaev/angular4-docker-example worked like a charm.

**Comment by JackMorrissey** [comment]
Hey @Phrohdoh, all set. I've merged #3  . Thanks for the contribution. Sorry for the delay, apparently I wasn't watching this repo...
