### ISSUE TITLE
Ignore emojis when testing for retirement-type contributions

### ISSUE THREAD

**Issue by jaysonsmith** [JackMorrissey/beyond-rule-4#28]
https://github.com/JackMorrissey/beyond-rule-4/blob/0d2ea9bc8876a4ce1259cd6a5330209323285c4a/src/app/forecasting/input/ynab/ynab.component.ts#L306

If a user has emoji'd - up their categories, these filters won't match automatically. Perhaps substring search or something of the sort, or something to filter emojis from the comparisons.

**Comment by JackMorrissey** [comment]
Thanks for the suggestion @jaysonsmith. I did a substring search and threw in a few additional emojis to look for for each section while I was at it. Please give it a whirl and let me know if that works for you.

**Comment by jaysonsmith** [comment]
Works great, thanks!
