### ISSUE TITLE
Add ability to incorporate YNAB Hidden Categories

### ISSUE THREAD

**Issue by KirkDahl** [JackMorrissey/beyond-rule-4#63]
If not already accounted for, it would be great if Hidden Categories affected the annual expenses calculation with an option to enable and disable it. It would also be great to show the hidden categories in the "Expense Impact on FI Date" section.

Sometimes I forget that I have all my categories for previous vacations hidden and those expenses aren't captured in the annual expense calculation, which throws off all of the FI calculations. I am editing my budget categories to reassign expenses from my specific vacation categories to a generic "Vacations" category that is always unhidden on my budget. I'm simplifying my budget by reassigning my hidden categories to the most closely related unhidden categories. This allows a more accurate calculation of annual expenses in BR4, but a switch to include/exclude hidden categories wouldn't require the user to edit their budget like this. I think the "ghost emoji" is still a good way to ignore any categories of the users choosing ("Finally, any category groups with names containing 👻 are completely ignored from the software.")

Of course, this is only possible if the YNAB API allows grabbing information from Hidden Categories.

**Comment by JackMorrissey** [comment]
Hey @KirkDahl, thanks for the feedback. The hidden categories are returned by the API and I'm actually currently actively excluding them. I can add a toggle. I almost have it working but will have to pick it up again, just have a few bugs to work out.

**Comment by KirkDahl** [comment]
Hi @JackMorrissey, awesome! Thanks for taking some time to start implementing this, your work is much appreciated!

**Comment by JackMorrissey** [comment]
Hey @KirkDahl, when you get a chance will you give that a try and let me know if that works for you?

**Comment by KirkDahl** [comment]
Hey @JackMorrissey, thank you so much for adding this feature! It works as intended!
I'm not sure if it's just my browser, but the category columns are cut off a bit. I'm not sure if this bug was caused by this new feature.
![image](https://user-images.githubusercontent.com/98568571/156944530-63773fc1-268e-491c-b5fb-5a27d7a5b138.png)

**Comment by JackMorrissey** [comment]
Ah maybe one of your newly exposed category names is super long? I probably
just need to set a min width for those other columns.

**Comment by JackMorrissey** [comment]
@KirkDahl Alright, I pushed a slight style change to better handle really long names. Give it a go? If that doesn't work for you, will you open a new ticket with some details so I can debug please?

**Comment by KirkDahl** [comment]
@JackMorrissey It works perfectly now! I have some long category names but now they have wrapped text and none of the columns are cut off. Thank you!
